bitcode_files:
  - artefacts/bc/APFloat.cpp.bc
  - artefacts/bc/APFloatTest.cpp.bc
  - artefacts/bc/APInt.cpp.bc
  - artefacts/bc/APIntTest.cpp.bc
  - artefacts/bc/APSInt.cpp.bc
  - artefacts/bc/APSIntTest.cpp.bc
  - artefacts/bc/ARMBuildAttrs.cpp.bc
  - artefacts/bc/ARMWinEH.cpp.bc
  - artefacts/bc/Allocator.cpp.bc
  - artefacts/bc/ArrayRefTest.cpp.bc
  - artefacts/bc/AsmMatcherEmitter.cpp.bc
  - artefacts/bc/AsmWriterEmitter.cpp.bc
  - artefacts/bc/AsmWriterInst.cpp.bc
  - artefacts/bc/Atomic.cpp.bc
  - artefacts/bc/Attributes.cpp.bc
  - artefacts/bc/BitVectorTest.cpp.bc
  - artefacts/bc/BitmaskEnumTest.cpp.bc
  - artefacts/bc/BlockFrequency.cpp.bc
  - artefacts/bc/BranchProbability.cpp.bc
  - artefacts/bc/COM.cpp.bc
  - artefacts/bc/CTagsEmitter.cpp.bc
  - artefacts/bc/CachePruning.cpp.bc
  - artefacts/bc/CallingConvEmitter.cpp.bc
  - artefacts/bc/CodeEmitterGen.cpp.bc
  - artefacts/bc/CodeGenDAGPatterns.cpp.bc
  - artefacts/bc/CodeGenInstruction.cpp.bc
  - artefacts/bc/CodeGenMapTable.cpp.bc
  - artefacts/bc/CodeGenRegisters.cpp.bc
  - artefacts/bc/CodeGenSchedule.cpp.bc
  - artefacts/bc/CodeGenTarget.cpp.bc
  - artefacts/bc/CommandLine.cpp.bc
  - artefacts/bc/Compression.cpp.bc
  - artefacts/bc/ConvertUTF.c.bc
  - artefacts/bc/ConvertUTFWrapper.cpp.bc
  - artefacts/bc/CrashRecoveryContext.cpp.bc
  - artefacts/bc/DAGDeltaAlgorithm.cpp.bc
  - artefacts/bc/DAGDeltaAlgorithmTest.cpp.bc
  - artefacts/bc/DAGISelEmitter.cpp.bc
  - artefacts/bc/DAGISelMatcher.cpp.bc
  - artefacts/bc/DAGISelMatcherEmitter.cpp.bc
  - artefacts/bc/DAGISelMatcherGen.cpp.bc
  - artefacts/bc/DAGISelMatcherOpt.cpp.bc
  - artefacts/bc/DFAPacketizerEmitter.cpp.bc
  - artefacts/bc/DataExtractor.cpp.bc
  - artefacts/bc/DataStream.cpp.bc
  - artefacts/bc/Debug.cpp.bc
  - artefacts/bc/DeltaAlgorithm.cpp.bc
  - artefacts/bc/DeltaAlgorithmTest.cpp.bc
  - artefacts/bc/DenseMapTest.cpp.bc
  - artefacts/bc/DenseSetTest.cpp.bc
  - artefacts/bc/DisassemblerEmitter.cpp.bc
  - artefacts/bc/Dwarf.cpp.bc
  - artefacts/bc/DynamicLibrary.cpp.bc
  - artefacts/bc/Errno.cpp.bc
  - artefacts/bc/Error.cpp.bc
  - artefacts/bc/ErrorHandling.cpp.bc
  - artefacts/bc/Error_Support.cpp.bc
  - artefacts/bc/FastISelEmitter.cpp.bc
  - artefacts/bc/FileOutputBuffer.cpp.bc
  - artefacts/bc/FileUtilities.cpp.bc
  - artefacts/bc/FixedLenDecoderEmitter.cpp.bc
  - artefacts/bc/FoldingSet.cpp.bc
  - artefacts/bc/FoldingSet_Support.cpp.bc
  - artefacts/bc/FormattedStream.cpp.bc
  - artefacts/bc/FunctionRefTest.cpp.bc
  - artefacts/bc/GraphWriter.cpp.bc
  - artefacts/bc/Hashing.cpp.bc
  - artefacts/bc/HashingTest.cpp.bc
  - artefacts/bc/Host.cpp.bc
  - artefacts/bc/ImmutableMapTest.cpp.bc
  - artefacts/bc/ImmutableSetTest.cpp.bc
  - artefacts/bc/InstrInfoEmitter.cpp.bc
  - artefacts/bc/IntEqClasses.cpp.bc
  - artefacts/bc/IntEqClassesTest.cpp.bc
  - artefacts/bc/IntervalMap.cpp.bc
  - artefacts/bc/IntervalMapTest.cpp.bc
  - artefacts/bc/IntrinsicEmitter.cpp.bc
  - artefacts/bc/IntrusiveRefCntPtr.cpp.bc
  - artefacts/bc/IntrusiveRefCntPtrTest.cpp.bc
  - artefacts/bc/JamCRC.cpp.bc
  - artefacts/bc/LEB128.cpp.bc
  - artefacts/bc/LineIterator.cpp.bc
  - artefacts/bc/Locale.cpp.bc
  - artefacts/bc/LockFileManager.cpp.bc
  - artefacts/bc/MD5.cpp.bc
  - artefacts/bc/Main.cpp.bc
  - artefacts/bc/MakeUniqueTest.cpp.bc
  - artefacts/bc/ManagedStatic.cpp.bc
  - artefacts/bc/MapVectorTest.cpp.bc
  - artefacts/bc/MathExtras.cpp.bc
  - artefacts/bc/Memory.cpp.bc
  - artefacts/bc/MemoryBuffer.cpp.bc
  - artefacts/bc/MemoryObject.cpp.bc
  - artefacts/bc/Mutex.cpp.bc
  - artefacts/bc/OptParserEmitter.cpp.bc
  - artefacts/bc/OptionalTest.cpp.bc
  - artefacts/bc/Options.cpp.bc
  - artefacts/bc/PackedVectorTest.cpp.bc
  - artefacts/bc/Path.cpp.bc
  - artefacts/bc/PluginLoader.cpp.bc
  - artefacts/bc/PointerEmbeddedIntTest.cpp.bc
  - artefacts/bc/PointerIntPairTest.cpp.bc
  - artefacts/bc/PointerSumTypeTest.cpp.bc
  - artefacts/bc/PointerUnionTest.cpp.bc
  - artefacts/bc/PostOrderIteratorTest.cpp.bc
  - artefacts/bc/PrettyStackTrace.cpp.bc
  - artefacts/bc/PriorityWorklistTest.cpp.bc
  - artefacts/bc/Process.cpp.bc
  - artefacts/bc/Program.cpp.bc
  - artefacts/bc/PseudoLoweringEmitter.cpp.bc
  - artefacts/bc/RWMutex.cpp.bc
  - artefacts/bc/RandomNumberGenerator.cpp.bc
  - artefacts/bc/RangeAdapterTest.cpp.bc
  - artefacts/bc/Record.cpp.bc
  - artefacts/bc/Regex.cpp.bc
  - artefacts/bc/RegisterInfoEmitter.cpp.bc
  - artefacts/bc/SCCIteratorTest.cpp.bc
  - artefacts/bc/SHA1.cpp.bc
  - artefacts/bc/ScaledNumber.cpp.bc
  - artefacts/bc/ScopedPrinter.cpp.bc
  - artefacts/bc/SearchForAddressOfSpecialSymbol.cpp.bc
  - artefacts/bc/SearchableTableEmitter.cpp.bc
  - artefacts/bc/SequenceTest.cpp.bc
  - artefacts/bc/SetTheory.cpp.bc
  - artefacts/bc/SetVectorTest.cpp.bc
  - artefacts/bc/Signals.cpp.bc
  - artefacts/bc/SmallPtrSet.cpp.bc
  - artefacts/bc/SmallPtrSetTest.cpp.bc
  - artefacts/bc/SmallStringTest.cpp.bc
  - artefacts/bc/SmallVector.cpp.bc
  - artefacts/bc/SmallVectorTest.cpp.bc
  - artefacts/bc/SourceMgr.cpp.bc
  - artefacts/bc/SparseBitVectorTest.cpp.bc
  - artefacts/bc/SparseMultiSetTest.cpp.bc
  - artefacts/bc/SparseSetTest.cpp.bc
  - artefacts/bc/SpecialCaseList.cpp.bc
  - artefacts/bc/Statistic.cpp.bc
  - artefacts/bc/StreamingMemoryObject.cpp.bc
  - artefacts/bc/StringExtras.cpp.bc
  - artefacts/bc/StringMap.cpp.bc
  - artefacts/bc/StringMapTest.cpp.bc
  - artefacts/bc/StringMatcher.cpp.bc
  - artefacts/bc/StringPool.cpp.bc
  - artefacts/bc/StringRef.cpp.bc
  - artefacts/bc/StringRefTest.cpp.bc
  - artefacts/bc/StringSaver.cpp.bc
  - artefacts/bc/SubtargetEmitter.cpp.bc
  - artefacts/bc/SystemUtils.cpp.bc
  - artefacts/bc/TGLexer.cpp.bc
  - artefacts/bc/TGParser.cpp.bc
  - artefacts/bc/TableGen.cpp.bc
  - artefacts/bc/TableGenBackend.cpp.bc
  - artefacts/bc/TargetParser.cpp.bc
  - artefacts/bc/TargetRegistry.cpp.bc
  - artefacts/bc/TestMain.cpp.bc
  - artefacts/bc/ThreadLocal.cpp.bc
  - artefacts/bc/ThreadPool.cpp.bc
  - artefacts/bc/Threading.cpp.bc
  - artefacts/bc/TimeValue.cpp.bc
  - artefacts/bc/Timer.cpp.bc
  - artefacts/bc/TinyPtrVectorTest.cpp.bc
  - artefacts/bc/ToolOutputFile.cpp.bc
  - artefacts/bc/Triple.cpp.bc
  - artefacts/bc/TripleTest.cpp.bc
  - artefacts/bc/Twine.cpp.bc
  - artefacts/bc/TwineTest.cpp.bc
  - artefacts/bc/Unicode.cpp.bc
  - artefacts/bc/Valgrind.cpp.bc
  - artefacts/bc/VariadicFunctionTest.cpp.bc
  - artefacts/bc/Watchdog.cpp.bc
  - artefacts/bc/X86DisassemblerTables.cpp.bc
  - artefacts/bc/X86ModRMFilters.cpp.bc
  - artefacts/bc/X86RecognizableInstr.cpp.bc
  - artefacts/bc/YAMLParser.cpp.bc
  - artefacts/bc/YAMLTraits.cpp.bc
  - artefacts/bc/circular_raw_ostream.cpp.bc
  - artefacts/bc/gtest-all.cc.bc
  - artefacts/bc/ilistTest.cpp.bc
  - artefacts/bc/raw_os_ostream.cpp.bc
  - artefacts/bc/raw_ostream.cpp.bc
  - artefacts/bc/regcomp.c.bc
  - artefacts/bc/regerror.c.bc
  - artefacts/bc/regexec.c.bc
  - artefacts/bc/regfree.c.bc
  - artefacts/bc/regstrlcpy.c.bc
